name: release

on:
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install_node
        uses: actions/setup-node@v2
      - name: install_yarn
        run: npm install -g yarn && yarn install
      - name: build
        run: yarn build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.run_number }} 
          tag_name: ${{ github.run_number }}
          body: |
            New Version
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: create zip
        uses: papeloto/action-zip@v1
        with:
          files: mongo_server
          dest: mongo_server.zip
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/installer/installer.exe
          asset_name: chm_installer-${{ github.run_number }}.exe
          asset_content_type: application/octet-stream
      - name: upload mongodb server zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mongo_server.zip
          asset_name: mongo_server.zip
          asset_content_type: application/gzip
