name: release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install_yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: create_dist
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: dist
      - name: build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: |
            New Version
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app-win32-ia32/app.exe
          asset_name: app.exe
          asset_content_type: application/octet-stream
